id: A8792F954
title: Aspiration Written on the Occasion of Princess Sangdé’s Passing in Sikkim
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:41.214103
  last_modified_at: 2022-03-01 05:48:41.214112
