id: A8792F954
title: Offering to the NÄgas of Gangtok
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:41.218089
  last_modified_at: 2022-03-01 05:48:41.218094
