id: A8792F954
title: 'Burgeoning Joy and Happiness: An Aspiration for the Welfare of the Great Hidden
  Land of Sikkim'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:41.216730
  last_modified_at: 2022-03-01 05:48:41.216734
